"""Compatibility adapter exposing persistence operations for handlers.

Handlers should depend on this adapter (or services/repositories), not
directly on ``aird.db``.
"""

from aird.db import (
    authenticate_user,
    create_network_share,
    create_user,
    delete_network_share,
    delete_share,
    delete_user,
    get_all_network_shares,
    get_all_shares,
    get_all_users,
    get_audit_logs,
    get_share_by_id,
    get_share_download_count,
    get_shares_for_path,
    get_user_by_username,
    get_user_favorites,
    get_user_quota,
    insert_share,
    is_share_expired,
    load_allowed_extensions,
    load_feature_flags,
    log_audit,
    save_allowed_extensions,
    save_feature_flags,
    save_upload_config,
    save_websocket_config,
    search_users,
    toggle_favorite,
    update_network_share,
    update_share,
    update_user,
    update_user_used_bytes,
)

__all__ = [
    "authenticate_user",
    "create_network_share",
    "create_user",
    "delete_network_share",
    "delete_share",
    "delete_user",
    "get_all_network_shares",
    "get_all_shares",
    "get_all_users",
    "get_audit_logs",
    "get_share_by_id",
    "get_share_download_count",
    "get_shares_for_path",
    "get_user_by_username",
    "get_user_favorites",
    "get_user_quota",
    "insert_share",
    "is_share_expired",
    "load_allowed_extensions",
    "load_feature_flags",
    "log_audit",
    "save_allowed_extensions",
    "save_feature_flags",
    "save_upload_config",
    "save_websocket_config",
    "search_users",
    "toggle_favorite",
    "update_network_share",
    "update_share",
    "update_user",
    "update_user_used_bytes",
]
